spring:
  application:
    name: OrderSystem-Core
  data:
    mongodb:
      uri: mongodb://order-app:qwerty@localhost:27117/ordersystem
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: order-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9094

server:
  port: 8082
